Merge Bshortall fork into main
BostonUniversitySeniorDesign/brain-4ce pull request #23
Opened 2023-04-30 21:20 UTC by Bshortall

2023-04-30 21:39 UTC, jonathanm-12 commented
Do we need the .vscode directory?

2023-05-04 00:41 UTC, mgilmore42 requested changes

2023-05-04 00:41 UTC, mgilmore42 commented on Model/trained_models/epoch_FBC_000.pth
please remove from commit.

2023-05-04 00:41 UTC, mgilmore42 commented on Model/trained_models/epoch_FBC_090.pth
Please remove from commit.

2023-05-04 00:41 UTC, mgilmore42 commented on Model/trained_models/results.csv
please remove from commit

2023-05-04 00:41 UTC, mgilmore42 commented on Model/.vscode/launch.json
please remove from commit

2023-05-04 00:54 UTC, mgilmore42 approved these changes
looks good

2023-05-04 18:03 UTC, jonathanm-12 approved these changes

2023-05-04 18:03 UTC, merged