Socket programs  to transfer data line by line
BostonUniversitySeniorDesign/brain-4ce pull request #9
Opened 2023-04-01 19:33 UTC by dayannat

2023-04-02 02:25 UTC, jonathanm-12 commented
This is amazing work

We might want to try avoiding the usage of an external csv but since you were facing problems with data loss it's understandable. I'm sure we can experiment with many different approaches 

Maybe we can try exporting the data (within python) as a pandas table so that it can be parsed easier 

Kind of tricky to write, open, and read from a csv from multiple simultaneous processes 

I can try making a simple gui for this as well for ease of interaction

Goal is to implement this with brainflow, virtual env, and LSTM

2023-04-02 02:26 UTC, jonathanm-12 approved these changes, later dismissed

2023-04-02 19:26 UTC, mgilmore42 commented
It looks like a good proof of concept and can definitely be in its current state used as an example implementation of using sockets, but given the way it is currently written (with lack of generality and extensibility) is not tenable to be embedded into the other processes. If this is the intention we can place it in documentation, otherwise additional effort will be required in order to improve its generality to be used in child processes. Please comment on the intention?

2023-04-03 20:03 UTC, jonathanm-12 commented
canceled my approval since this is still WIP, looking forward to see what you do with it

2023-04-03 20:30 UTC, dayannat commented
This was meant to be a proof of concept for transferring data. That part is now working.

Still need to work on generalizing. Am currently exploring the PR made by Mitchell on 4/02 for getting data from the headset. Once that is working, will move onto the virtual environment.

2023-04-07 19:45 UTC, jonathanm-12 submitted a review, later dismissed

2023-04-19 21:15 UTC, jonathanm-12 commented
Could you add comments in your code to indicate which parts of the work were written by you?

2023-04-20 19:34 UTC, Bshortall approved these changes

2023-04-20 19:47 UTC, mgilmore42 commented
@dayannat Please address my review comments. Additionally the the socket programming looks good. The ML code looks to be in a rough state (not in conformance with current PyTorch versions). In order to get your contributions in the main branch I would suggest making seperate PRs for the one for the socket programming and one for the ML. That way we can get the socket programming up streamed while we correct the ML code.

2023-04-24 19:20 UTC, mgilmore42 requested changes

2023-04-24 19:20 UTC, mitch-gilmore commented on EEG Classification (ML)/CNN.ipynb
Can you please convert this to a python script? Jupyter notebooks tend to be a pain for VC integration since is save the outputs within the file. See line 149-152 for example. It would also make it easier to review.

2023-04-24 19:20 UTC, mitch-gilmore commented on EEG Classification (ML)/Train_Model.py
> +                    best_model = copy.deepcopy(model)
This is not the standard way of taking a model snap shot and could cause problems if the model is in cuda memory. See [here](https://brsoff.github.io/tutorials/beginner/saving_loading_models.html#id3) for standard practices.

2023-04-24 19:20 UTC, mitch-gilmore commented on EEG Classification (ML)/Train_Model.py
> +                    running_corrects += torch.sum(preds.data.max(1)[1] ==
Not sure if its a bug or not, but I have never seen a `data` member for Tensors. preds and labels are Tensors right? Also could not find anything in their documentation for Tensors about it.

2023-04-24 19:20 UTC, mitch-gilmore commented on EEG Classification (ML)/Train_Model.py
> +                    running_corrects += torch.sum(preds.data.max(1)[1] ==
I found a link [here](https://stackoverflow.com/questions/51743214/is-data-still-useful-in-pytorch) explaining the `data` member. The overview is that using it currently shouldn't work if its a `Tensor`.

2023-04-30 21:39 UTC, closed without merging